# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- none

schedules:
  - cron: "0 0 * * *"
    displayName: Daily Portal Smoke Test
    branches:
      include:
        - master
    always: true

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: npm ci
  displayName: 'Install Dependencies'

- script: npx cypress verify
  displayName: 'Check Cypress Installation'

- script: npx cypress run 
  displayName: 'Run Cypress Tests'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'cypress/reports/mochawesome'
    artifact: 'MochawesomeReport'
    publishLocation: 'pipeline'
  condition: succeededOrFailed()
  
- script: |
    npx mochawesome-merge cypress/reports/mochawesome/*.json > cypress/reports/mochawesome/merged-report.json
    npx mochawesome-report-generator cypress/reports/mochawesome/merged-report.json
  displayName: 'Generate final HTML report'